### ISSUE TITLE
Create threads in field-specific channels?

### ISSUE THREAD

**Issue by sahuang** [Leslato/Discord_bot-CTFD-Thread-Parser#1]
Thanks for the tool, it seems pretty useful since we now manually create threads in CTF category.

One improvement that I think would be really nice - right now we create different channels in a CTF category, e.g. Crypto/Web/Misc/Pwn/Rev/OSINT etc. The information is in CTFD platform. It would be much better to categorize threads according to their field so we can discuss and find threads easier.

**Comment by Leslato** [comment]
Yes indeed it was our first idea, but in the end we decided to do it like this to make it easier to archive in, for example, a category 'end CTF', otherwise the discord would be full very quickly, but it is a modification that can be done :)

Anyway, thanks for the suggestion.

**Comment by sahuang** [comment]
Thanks, yeah I agree archiving would be an issue. This seems a dilemma lol, if only we can in the end "merge" all channels' threads into a newly created channel by copying message or sth, that would be better.
